//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Segundaentrega.rc
//
#define IDC_MYICON                      2
#define IDC_STATIC3                     4
#define IDD_SEGUNDAENTREGA_DIALOG       102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_SEGUNDAENTREGA              107
#define IDI_SMALL                       108
#define IDC_SEGUNDAENTREGA              109
#define IDR_MAINFRAME                   128
#define DLG_INICIARSESION               129
#define DLG_REGISTROUSUARIO             130
#define DLG_INFORMACIONVENDEDOR         131
#define DLG_MISENVIOS                   132
#define IDR_MENU1                       133
#define DLG_CANCELARENVIO               134
#define DLG_EDITARENVIO                 135
#define DLG_COMPRARPRODUCTOS            136
#define DLG_NUEVOPRODUCTO               137
#define DLG_ELIMINARPRODUCTO            138
#define DLG_EDITARPRODUCTO              139
#define DLG_MISPRODUCTOS                140
#define DLG_SALIR                       141
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT5                       1002
#define BTN_REGISTRARTE                 1002
#define IDC_EDIT6                       1003
#define BTN_REGRESAR                    1003
#define IDC_EDIT3                       1004
#define IDC_EDIT7                       1005
#define TXT_CODIGOEDITADO               1005
#define IDC_EDIT8                       1006
#define TXT_DESCRIPCIONEDITADA          1007
#define TXT_PASSWORDREGISTRO            1008
#define IDC_EDIT10                      1008
#define TXT_MONTOEDITADO                1008
#define IDC_STATIC4                     1010
#define BTN_ALTAVENDEDOR                1011
#define BTN_EDITARVENDEDOR              1012
#define LB_CARACTERISTICAS              1013
#define IDC_COMBO1                      1015
#define IDCANCELAR                      1016
#define IDASIGNAR                       1017
#define BTN_CARGARIMAGEN                1021
#define BTN_CARGARIMAGEN2               1022
#define BTN_ELIMINARPRODUCTO            1023
#define BTN_CONFIRMAREDICION            1025
#define BTN_SALIR1                      1026
#define BTN_REGISTRAR                   1027
#define IDC_BUTTON1                     1028
#define BTN_SALIR2                      1029
#define Imagen3                         1033
#define BTN_INICIARSESION               1035
#define BTN_CANCELAR                    1036
#define TXT_RUTAVENDEDOR                1037
#define PC_INFORMACIONVENDEDOR          1038
#define PC_PRODUCTO                     1039
#define TXT_RUTAPRODUCTO                1040
#define IDC_DATETIMEPICKER              1041
#define TXT_USUARIOREGISTRO             1042
#define PC_CANCELARENVIO                1043
#define PC_MISENVIOS                    1044
#define TXT_USUARIOINICIAR              1045
#define TXT_PASSWORDINICIAR             1046
#define PC_PRODUCTO2                    1047
#define TXT_RUTAPRODUCTO2               1048
#define BTN_CARGARIMAGEN3               1049
#define TXT_NOMBREDELVENDEDOR           1050
#define TXT_ALIASDELAEMPRESA            1051
#define TXT_NOMBREDELPRODUCTO           1052
#define TXT_CANTIDADENINVENTARIO        1053
#define TXT_CODIGODELPRODUCTO           1054
#define TXT_MARCA                       1055
#define TXT_DESCRIPCION                 1056
#define TXT_MONTO                       1057
#define BTN_AGREGARPRODUCTO             1058
#define TXT_BUSCARNOMBRE                1059
#define BTN_MOSTRAR                     1060
#define TXT_CARACTERISTICAS             1061
#define TXT_EDITARPRODUCTO              1062
#define TXT_NOMBREEDITADO               1064
#define TXT_MARCAEDITADA                1065
#define LB_CARACTERISTICAS2             1067
#define LB_PRODUCTOSDADOSDEALTA         1068
#define BTN_MISCARACTERISTICAS          1069
#define LB_PRODUCTOSDADOSDEALTA2        1070
#define ID_INFORMACI32771               32771
#define ID_INFORMACI32772               32772
#define ID_INFORMACI32773               32773
#define ID_ENV32775                     32775
#define ID_ENV32776                     32776
#define ID_ENV32777                     32777
#define ID_ENV32778                     32778
#define ID_PRODUCTOS_NUEVOPRODUCTO      32779
#define ID_PRODUCTOS_EDITARPRODUCTO     32781
#define ID_PRODUCTOS_MISPRODUCTOS       32782
#define ID_PRODUCTOS_ELIMINARPRODUCTO   32784
#define ID_COMPRARPRODUCTOS             32785
#define ID_CANCELARUNENVIO              32786
#define ID_EDITARUNENVIO                32787
#define ID_MISENVIOS                    32788
#define ID_INFORMACIONVENDEDOR          32789
#define ID_SALIRMENU                    32790
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
